// src/pages/donations.jsx
import React from 'react';

import Layout from '../components/layout';

const Donations = () => (
  <Layout title="Donations">
    <h2>Donations</h2>
    <p>
      Each year we accept donations of canned goods for the Nashua Soup Kitchen and Shelter. Donations of canned goods for the Nashua Soup Kitchen and
      Shelter will be accepted on Wednesday, November 22nd 10:00am to 5:00pm AND race day morning in the Nashua South cafeteria. Thank you for your
      generosity!
    </p>
    <p>
      Monetary donations to the Nashua Cross Country and Track programs will also be accepted through the registration page and in-person at bib pickup and race day.
    </p>
  </Layout>
)

export default Donations;

// src/routes/donations/+page.svelte
<h2>Donations</h2>
<p>
  Each year we accept donations of canned goods for the Nashua Soup Kitchen and Shelter. Donations
  of canned goods for the Nashua Soup Kitchen and Shelter will be accepted on Wednesday, November
  26th 10:00am to 5:00pm AND race day morning in the Nashua South cafeteria. Thank you for your
  generosity!
</p>
<p>
  Monetary donations to the Nashua Cross Country and Track programs will also be accepted through
  the registration page and in-person at bib pickup and race day.
</p>
